### ISSUE TITLE
Question about the code implemenation of the AFFNet

### ISSUE THREAD

**Issue by csguoh** [microsoft/ActiveMLP#17]
Hi author,
Thanks for your incredible work! I have a question about the code implementation of the ICCV23 paper Adaptive Frequency Filters As Efficient Global Token Mixers.
After the Fourier Transform, instead of mapping the real and imaginary parts with two mlp layer, why use `real - imaginary` and `real + imaginary` to get `o1_real` and `o1_imag` this [line](https://github.com/microsoft/TokenMixers/blob/99dbe38c2a5c3ea3c655b8c42c763a6d595e18f9/Adaptive%20Frequency%20Filters/affnet/modules/aff_block.py#L121). Are there any insights here?

**Comment by hzphzp** [comment]
Sorry for the late response. This operation treats the MLP weights as complex numbers, performing complex multiplication calculations.

**Comment by csguoh** [comment]
Got it! Thanks for your reply:D
